-- Crear la tabla "PERSONAS"
CREATE TABLE PERSONAS (
    ID_PERSONA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    APELLIDO_MATERNO TEXT NOT NULL,
    APELLIDO_PATERNO TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);

-- Insertar los registros
INSERT INTO PERSONAS (NOMBRE, APELLIDO_MATERNO, APELLIDO_PATERNO, EMAIL)
VALUES ('Juan', 'Pérez', 'González', 'juan.perez@example.com');

INSERT INTO PERSONAS (NOMBRE, APELLIDO_MATERNO, APELLIDO_PATERNO, EMAIL)
VALUES ('María', 'García', 'Hernández', 'maria.garcia@example.com');

INSERT INTO PERSONAS (NOMBRE, APELLIDO_MATERNO, APELLIDO_PATERNO, EMAIL)
VALUES ('Luis', 'Sánchez', 'Martínez', 'luis.sanchez@example.com');

